---
- src: "geerlingguy.firewall"
- src: "geerlingguy.security"
- src: "geerlingguy.java"
- src: "williamyeh.reset-locale"
- src: "williamyeh.uwsgi"
- src: "geerlingguy.nginx"
- src: "geerlingguy.postfix"
